Trabalho PCG Grupo:
- Breno Monteiro Amaral
- Bruno Amaral Gonzalez
- Enzo Liutkus Going
- Emanuel Rodirguers Soares
- Leandro Corso

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
arquivo = '/content/drive/MyDrive/ColabNotebooks/exporta.xls'

import pandas as pd
df = pd.read_excel(arquivo)
df.columns = df.loc[0]
df.columns.values[0] = 'mês-ano'
df = df[1:-3].replace(to_replace=r'\r', value='', regex=True)
df

0    mês-ano Belo Horizonte Rio de Janeiro São Paulo  Vitória
1    01-1989        145h04m        154h04m   154h45m  146h31m
2    02-1989        175h35m        178h32m   176h22m  179h36m
3    03-1989        190h09m        194h04m   194h21m  187h23m
4    04-1989        192h15m        197h49m   207h03m  202h12m
5    05-1989        188h04m        197h16m   197h01m  203h48m
..       ...            ...            ...       ...      ...
429  08-2024        102h05m        116h11m   122h31m  106h36m
430  09-2024        101h30m        117h59m   123h28m  108h16m
431  10-2024        105h39m        120h33m   125h34m  110h19m
432  11-2024        107h01m        121h10m   129h04m  113h12m
433  12-2024        108h15m        121h30m   131h05m  116h27m

[433 rows x 5 columns]

In [ ]:
# prompt: quero converter string formato 121h10m em minutos (inteiro) num dataframe

import re

def convert_to_minutes(time_str):
  """Converts a string in 'HHhMMm' format to minutes (integer)."""
  try:
    match = re.match(r'(\d+)h(\d+)m', time_str)
    if match:
      hours = int(match.group(1))
      minutes = int(match.group(2))
      return hours * 60 + minutes
    else:
      return 0  # Or handle invalid format as needed
  except (ValueError, AttributeError, TypeError):
    return 0 # Or handle invalid format as needed




for col in df.columns:
  if(col == 'mes-ano'): continue
  df[col] = df[col].apply(convert_to_minutes)

In [ ]:
import plotly.express as px
ano = '1989'

fig = px.line(df, x='mes-ano', y=['Belo Horizonte', 'Rio de Janeiro'], title='Horas trabalhadas')
fig.show()

In [ ]:
arquivo = '/content/drive/MyDrive/ColabNotebooks/exporta.xls'

import pandas as pd
df = pd.read_excel(arquivo)
df.columns = df.loc[0]
df.columns.values[0] = 'mês-ano'
df = df[1:-3].replace(to_replace=r'\r', value='', regex=True)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/ColabNotebooks/exporta.xls'

In [ ]:
import re

def convert_to_float(time_str):
  """Converts a string in 'HHhMMm' format to a float 'HH.MM'."""
  try:
    match = re.match(r'(\d+)h(\d+)m', time_str)
    if match:
      hours = int(match.group(1))
      minutes = int(match.group(2))
      return float(f"{hours}.{minutes:02d}")
    else:
      return 0.0
  except (ValueError, AttributeError, TypeError):
    return 0.0

for col in df.columns:
  if(col == 'mês-ano'): continue
  df[col] = df[col].apply(convert_to_float)

print(df)

0    mês-ano  Belo Horizonte  Rio de Janeiro  São Paulo  Vitória
1    01-1989          145.04          154.04     154.45   146.31
2    02-1989          175.35          178.32     176.22   179.36
3    03-1989          190.09          194.04     194.21   187.23
4    04-1989          192.15          197.49     207.03   202.12
5    05-1989          188.04          197.16     197.01   203.48
..       ...             ...             ...        ...      ...
429  08-2024          102.05          116.11     122.31   106.36
430  09-2024          101.30          117.59     123.28   108.16
431  10-2024          105.39          120.33     125.34   110.19
432  11-2024          107.01          121.10     129.04   113.12
433  12-2024          108.15          121.30     131.05   116.27

[433 rows x 5 columns]

# Gráficos Horas de trabalho

In [ ]:
import plotly.express as px

fig = px.line(df, x='mês-ano', y=df.columns.difference(['mês-ano']), title='Horas de trabalho (1989-2024)')
fig.show()

In [ ]:
import plotly.express as px

# Filtra o DataFrame para incluir apenas as linhas onde 'mes-ano' contém um ano até 2000
df_filtered = df[df['mês-ano'].str.contains(r'(19[0-9]{2}|2000)')]

fig = px.line(df_filtered, x='mês-ano', y=df_filtered.columns.difference(['mês-ano']), title='Horas de trabalho (1989-2000)')
fig.show()

<ipython-input-7-a56751f8030d>:4: UserWarning:

This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.

In [ ]:
import plotly.express as px

# Filtra o DataFrame para incluir apenas as linhas onde 'mes-ano' contém um ano entre 2000 e 2010
df_filtered_2000_2010 = df[df['mês-ano'].str.contains(r'(200[0-9]|2010)')]

fig = px.line(df_filtered_2000_2010, x='mês-ano', y=df_filtered_2000_2010.columns.difference(['mês-ano']), title='Horas de trabalho (2000-2010)')
fig.show()

<ipython-input-8-f245c340a938>:4: UserWarning:

This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.

In [ ]:
import plotly.express as px

# Filtra o DataFrame para incluir apenas as linhas onde 'mes-ano' contém um ano entre 2010 e 2020
df_filtered_2010_2020 = df[df['mês-ano'].str.contains(r'(201[0-9]|2020)')]

fig = px.line(df_filtered_2010_2020, x='mês-ano', y=df_filtered_2010_2020.columns.difference(['mês-ano']), title='Horas de trabalho (2010-2020)')
fig.show()

<ipython-input-9-2697fc8f11fc>:4: UserWarning:

This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.

In [ ]:
import plotly.express as px

# Filtra o DataFrame para incluir apenas as linhas onde 'mes-ano' contém um ano entre 2020 e 2025
df_filtered_2020_2025 = df[df['mês-ano'].str.contains(r'(202[0-5])')]

fig = px.line(df_filtered_2020_2025, x='mês-ano', y=df_filtered_2020_2025.columns.difference(['mês-ano']), title='Horas de trabalho (2020-2025) Nota: Falta de dados em "05-2021 Belo Horizonte"')
fig.show()

<ipython-input-12-c606d6e01b07>:4: UserWarning:

This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.

# Gráficos Preço da cesta básica

In [ ]:
arquivo = '/content/drive/MyDrive/ColabNotebooks/preçocesta.xlsx'

import pandas as pd
df = pd.read_excel(arquivo)
df.columns = df.loc[0]
df.columns.values[0] = 'mês-ano'
df = df[1:-3].replace(to_replace=r'\r', value='', regex=True)
df

<ipython-input-3-e0f364830cd1>:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df[1:-3].replace(to_replace=r'\r', value='', regex=True)

0    mês-ano  Belo Horizonte  Rio de Janeiro  São Paulo  Vitória
1    01-1989           42.14           44.75      44.95    42.56
2    02-1989           51.00           51.86      51.23    52.17
3    03-1989           55.23           56.37      56.45    54.43
4    04-1989           55.84           57.46      60.14    58.73
5    05-1989           69.59           72.99      72.90    75.41
..       ...             ...             ...        ...      ...
426  05-2024          693.39          796.67     826.85   723.91
427  06-2024          701.55          814.38     832.69   718.43
428  07-2024          656.69          757.64     809.77   688.45
429  08-2024          655.25          745.64     786.35   684.21
430  09-2024          651.44          757.30     792.47   694.87

[430 rows x 5 columns]

In [ ]:
import plotly.express as px

fig = px.line(df, x='mês-ano', y=df.columns.difference(['mês-ano']), title='Preço da cesta (Nota: O alto valor é devido a alta inflação do cruzeiro real entre os anos de 1990 e 1993)')
fig.show()

In [ ]:
import plotly.express as px

# Filtra o DataFrame para incluir apenas as linhas onde 'mês-ano' contém um ano entre 1995 e 2025
df_filtered_1995_2025 = df[df['mês-ano'].str.contains(r'(199[5-9]|20[0-2][0-9]|2025)')]

fig = px.line(df_filtered_1995_2025, x='mês-ano', y=df_filtered_1995_2025.columns.difference(['mês-ano']), title='Preço da cesta (1995-2025) (Nota: Apenas moeda Real)')
fig.show()

<ipython-input-29-cdd12c0b2d05>:4: UserWarning:

This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.

In [ ]:
import plotly.express as px

# Filtra o DataFrame para incluir apenas as linhas onde 'mes-ano' contém um ano entre 2000 e 2010
df_filtered_2000_2010 = df[df['mês-ano'].str.contains(r'(200[0-9]|2010)')]

fig = px.line(df_filtered_2000_2010, x='mês-ano', y=df_filtered_2000_2010.columns.difference(['mês-ano']), title='Preço da cesta (2000-2010)')
fig.show()

<ipython-input-30-7939722fd5d8>:4: UserWarning:

This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.

In [ ]:
import plotly.express as px

# Filtra o DataFrame para incluir apenas as linhas onde 'mes-ano' contém um ano entre 2010 e 2020
df_filtered_2010_2020 = df[df['mês-ano'].str.contains(r'(201[0-9]|2020)')]

fig = px.line(df_filtered_2010_2020, x='mês-ano', y=df_filtered_2010_2020.columns.difference(['mês-ano']), title='Preço da cesta (2010-2020)')
fig.show()

<ipython-input-18-8d8c89f6c297>:4: UserWarning:

This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.

In [ ]:
import plotly.express as px

# Filtra o DataFrame para incluir apenas as linhas onde 'mes-ano' contém um ano entre 2020 e 2025
df_filtered_2020_2025 = df[df['mês-ano'].str.contains(r'(202[0-5])')]

fig = px.line(df_filtered_2020_2025, x='mês-ano', y=df_filtered_2020_2025.columns.difference(['mês-ano']), title='Preço da cesta (2020-2025)')
fig.show()

<ipython-input-4-94da027fe22f>:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_filtered_2020_2025 = df[df['mês-ano'].str.contains(r'(202[0-5])')]

# Tabela Horas Trabalhadas (Média, Mediana e Desvio Geral)

In [ ]:
import pandas as pd
import numpy as num
from google.colab import data_table
data_table.enable_dataframe_formatter

def tempo_para_minutos(tempo_str):
    """Converte tempo em formato XXhXXm para minutos totais"""
    try:
        if pd.isna(tempo_str) or tempo_str == '':
            return None

        tempo_str = str(tempo_str).strip()

        # Extrair horas e minutos do formato "145h04m"
        if 'h' in tempo_str and 'm' in tempo_str:
            partes = tempo_str.replace('m', '').split('h')
            horas = int(partes[0])
            minutos = int(partes[1])
            return horas * 60 + minutos
        else:
            return None
    except:
        return None

def minutos_para_tempo(minutos):
    """Converte minutos totais de volta para formato XXhXXm"""
    if pd.isna(minutos) or minutos is None:
        return None

    minutos = int(minutos)
    h = minutos // 60
    m = minutos % 60
    return f"{h}h{m:02d}m"

# Carregar arquivo
arquivo = '/content/drive/MyDrive/exporta.xls'
df = pd.read_excel(arquivo)
df.columns = df.loc[0]
df.columns.values[0] = 'mes-ano'
df = df[1:-3].replace(to_replace=r'\r', value='', regex=True)

# Exibir dados originais
print("📊 DADOS ORIGINAIS:")
display(df)
# Filtrar dados a partir de 1998
df_filtered = df[df['mes-ano'].str.contains(r'(199[5-9]|20[0-9]{2})', na=False)]
print("DADOS FILTRADOS A PARTIR DE 1995:")
display(df_filtered)
df = df_filtered.copy()

# Vamos pegar todas as colunas a partir da 3ª (índice 2)
colunas_cidades = []
for i, col in enumerate(df.columns):
    # Pular apenas a primeira coluna (mes-ano)
    if i >= 1 and col is not None and str(col).strip() != '':
        # Verificar se não é uma coluna 'Unnamed'
        if not str(col).startswith('Unnamed'):
            colunas_cidades.append(col)

print(f"\n🏙️ Cidades identificadas: {colunas_cidades}")

# Processar cada cidade
resultados = []

for cidade in colunas_cidades:
    # Converter tempos para minutos
    minutos = df[cidade].apply(tempo_para_minutos)
    minutos_validos = minutos.dropna()

    if not minutos_validos.empty:
        media_min = minutos_validos.mean()
        mediana_min = minutos_validos.median()
        std_min = minutos_validos.std()

        resultados.append({
            'Cidade': cidade,
            'Registros': len(minutos_validos),
            'Média': minutos_para_tempo(media_min),
            'Mediana': minutos_para_tempo(mediana_min),
            'Desvio Padrão': minutos_para_tempo(std_min),
            'Mínimo': minutos_para_tempo(minutos_validos.min()),
            'Máximo': minutos_para_tempo(minutos_validos.max())
        })

# Criar DataFrame com resultados
if resultados:
    estatisticas = pd.DataFrame(resultados)

    print("\n📈 ESTATÍSTICAS POR CIDADE:")
    display(estatisticas)

    # Calcular estatística geral
    todos_minutos = []
    for cidade in colunas_cidades:
        minutos = df[cidade].apply(tempo_para_minutos).dropna()
        todos_minutos.extend(minutos.tolist())

    if todos_minutos:
        geral = pd.DataFrame({
            'Métrica': ['Geral (Todas as Cidades)'],
            'Total de Registros': [len(todos_minutos)],
            'Média Geral': [minutos_para_tempo(np.mean(todos_minutos))],
            'Mediana Geral': [minutos_para_tempo(np.median(todos_minutos))],
            'Desvio Padrão Geral': [minutos_para_tempo(np.std(todos_minutos))]
        })

        print("\n🌎 ESTATÍSTICA GERAL:")
        display(geral)

        #Display de média de horas por período
        print("\n📅 MÉDIA DE HORAS POR PERÍODO:")

        # Extrair ano da coluna mes-ano
        df_periodo = df.copy()
        df_periodo['ano'] = df_periodo['mes-ano'].str.extract(r'(\d{4})')

        # Calcular média por ano
        medias_periodo = []

        for ano in sorted(df_periodo['ano'].dropna().unique()):
            df_ano = df_periodo[df_periodo['ano'] == ano]

            # Calcular média de todas as cidades para este ano
            minutos_ano = []
            for cidade in colunas_cidades:
                minutos_cidade = df_ano[cidade].apply(tempo_para_minutos).dropna()
                minutos_ano.extend(minutos_cidade.tolist())

            if minutos_ano:
                media_ano = np.mean(minutos_ano)
                medias_periodo.append({
                    'Ano': int(ano),
                    'Média de Horas': minutos_para_tempo(media_ano),
                    'Registros': len(minutos_ano)
                })

        if medias_periodo:
            df_medias_periodo = pd.DataFrame(medias_periodo)
            display(df_medias_periodo)
    else:
      print("❌ Não foi possível processar os dados")
      print("Estrutura das colunas:", df.columns.tolist())
      print("Primeiras linhas:")
      display(df.head())

📊 DADOS ORIGINAIS:

0    mes-ano Belo Horizonte Rio de Janeiro São Paulo  Vitória
1    01-1989        145h04m        154h04m   154h45m  146h31m
2    02-1989        175h35m        178h32m   176h22m  179h36m
3    03-1989        190h09m        194h04m   194h21m  187h23m
4    04-1989        192h15m        197h49m   207h03m  202h12m
5    05-1989        188h04m        197h16m   197h01m  203h48m
..       ...            ...            ...       ...      ...
418  09-2023        105h38m        119h59m   122h28m  113h39m
419  10-2023        104h37m        120h11m   123h01m  112h32m
420  11-2023        106h37m        121h23m   124h53m  112h35m
421  12-2023        109h23m        123h06m   126h50m  114h49m
422  01-2024        112h55m        123h22m   123h37m  112h04m

[422 rows x 5 columns]

DADOS FILTRADOS A PARTIR DE 1995:

<ipython-input-32-aeaf30d55ee8>:46: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_filtered = df[df['mes-ano'].str.contains(r'(199[5-9]|20[0-9]{2})', na=False)]

0    mes-ano Belo Horizonte Rio de Janeiro São Paulo  Vitória
73   01-1995        208h08m        195h49m   224h41m  186h05m
74   02-1995        237h54m        236h16m   263h20m  230h09m
75   03-1995        246h52m        240h48m   278h38m  244h15m
76   04-1995        262h10m        272h23m   306h21m  268h25m
77   05-1995        187h44m        195h30m   203h44m  196h24m
..       ...            ...            ...       ...      ...
418  09-2023        105h38m        119h59m   122h28m  113h39m
419  10-2023        104h37m        120h11m   123h01m  112h32m
420  11-2023        106h37m        121h23m   124h53m  112h35m
421  12-2023        109h23m        123h06m   126h50m  114h49m
422  01-2024        112h55m        123h22m   123h37m  112h04m

[350 rows x 5 columns]

🏙️ Cidades identificadas: ['Belo Horizonte', 'Rio de Janeiro', 'São Paulo', 'Vitória']

📈 ESTATÍSTICAS POR CIDADE:

           Cidade  Registros    Média  Mediana Desvio Padrão  Mínimo   Máximo
0  Belo Horizonte        349  123h22m  113h02m        31h09m  82h32m  262h10m
1  Rio de Janeiro        350  128h05m  120h32m        28h50m  89h09m  272h23m
2       São Paulo        350  135h35m  126h19m        33h26m  96h39m  306h21m
3         Vitória        350  121h23m  113h36m        24h32m  90h26m  268h25m

🌎 ESTATÍSTICA GERAL:

,Métrica,Total de Registros,Média Geral,Mediana Geral,Desvio Padrão Geral
0,Geral (Todas as Cidades),1399,127h06m,118h04m,30h08m

📅 MÉDIA DE HORAS POR PERÍODO:

     Ano Média de Horas  Registros
0   1995        199h40m         48
1   1996        175h54m         48
2   1997        164h27m         48
3   1998        165h47m         48
4   1999        160h22m         48
5   2000        159h06m         48
6   2001        151h33m         48
7   2002        145h46m         48
8   2003        149h16m         48
9   2004        141h32m         48
10  2005        129h28m         48
11  2006        109h33m         48
12  2007        108h06m         48
13  2008        120h40m         48
14  2009        106h41m         48
15  2010        100h49m         48
16  2011        103h58m         48
17  2012         99h40m         48
18  2013        102h31m         48
19  2014        100h54m         48
20  2015        103h24m         52
21  2016        108h51m         48
22  2017         96h24m         48
23  2018         96h19m         48
24  2019        102h01m         48
25  2020        112h04m         48
26  2021        124h56m         47
27  2022        129h33m         48
28  2023        119h33m         48
29  2024        117h59m          4

#Tabela de Preços (Média, Mediana e Desvio Geral)

In [ ]:
import pandas as pd
import numpy as np


def limpar_valor_monetario(valor):
    """Converte valores monetários para float, tratando diferentes formatos"""
    try:
        if pd.isna(valor) or valor == '':
            return None

        # Converter para string e limpar
        valor_str = str(valor).strip()

        # Remover símbolos de moeda e espaços
        valor_limpo = valor_str.replace('R$', '').replace('$', '').replace(' ', '')

        # Tratar vírgula como separador decimal (formato brasileiro)
        if ',' in valor_limpo and '.' in valor_limpo:
            # Se tem ambos, vírgula é separador de milhar, ponto é decimal
            valor_limpo = valor_limpo.replace(',', '')
        elif ',' in valor_limpo:
            # Se só tem vírgula, é separador decimal
            valor_limpo = valor_limpo.replace(',', '.')

        return float(valor_limpo)
    except:
        return None

def formatar_moeda(valor):
    """Formata valor como moeda brasileira"""
    if pd.isna(valor) or valor is None:
        return None
    return f"R$ {valor:,.2f}".replace(',', 'X').replace('.', ',').replace('X', '.')

# Carregar arquivo
arquivo = '/content/drive/MyDrive/precocesta.xlsx'  # Ajuste o caminho conforme necessário
df = pd.read_excel(arquivo)

# Configurar cabeçalhos
df.columns = df.iloc[0]  # Usar primeira linha como cabeçalho
df.columns.values[0] = 'mes-ano'  # Renomear primeira coluna
df = df[1:].reset_index(drop=True)  # Remover linha de cabeçalho e resetar índice

# Limpar dados (remover quebras de linha)
df = df.replace(to_replace=r'\r|\n', value='', regex=True)

# Exibir dados originais
print("📊 DADOS ORIGINAIS:")
display(df)

# Filtrar dados a partir de 1995 (modificação principal)
df_filtered = df[df['mes-ano'].str.contains(r'(199[5-9]|20[0-9]{2})', na=False)]
print("DADOS FILTRADOS A PARTIR DE 1995:")
df_filtered

# Usar dados filtrados para análise
df = df_filtered.copy()

# Identificar colunas de cidades (todas exceto a primeira)
colunas_cidades = []
for i, col in enumerate(df.columns):
    if i >= 1 and col is not None and str(col).strip() != '':
        if not str(col).startswith('Unnamed'):
            colunas_cidades.append(col)

print(f"\n🏙️ Cidades identificadas: {colunas_cidades}")

# Processar cada cidade
resultados = []

for cidade in colunas_cidades:
    # Converter valores para float
    valores = df[cidade].apply(limpar_valor_monetario)
    valores_validos = valores.dropna()

    if not valores_validos.empty:
        media = valores_validos.mean()
        mediana = valores_validos.median()
        desvio_padrao = valores_validos.std()
        minimo = valores_validos.min()
        maximo = valores_validos.max()

        resultados.append({
            'Cidade': cidade,
            'Registros': len(valores_validos),
            'Média': formatar_moeda(media),
            'Mediana': formatar_moeda(mediana),
            'Desvio Padrão': formatar_moeda(desvio_padrao),
            'Mínimo': formatar_moeda(minimo),
            'Máximo': formatar_moeda(maximo),
            'Soma Total': formatar_moeda(valores_validos.sum())
        })

# Criar DataFrame com resultados
if resultados:
    estatisticas = pd.DataFrame(resultados)

    print("\n📈 ESTATÍSTICAS POR CIDADE (A PARTIR DE 1995):")
    display(estatisticas)

    # Calcular estatística geral
    todos_valores = []
    for cidade in colunas_cidades:
        valores = df[cidade].apply(limpar_valor_monetario).dropna()
        todos_valores.extend(valores.tolist())

    if todos_valores:
        geral = pd.DataFrame({
            'Métrica': ['Geral (Todas as Cidades)'],
            'Total de Registros': [len(todos_valores)],
            'Média Geral': [formatar_moeda(np.mean(todos_valores))],
            'Mediana Geral': [formatar_moeda(np.median(todos_valores))],
            'Desvio Padrão Geral': [formatar_moeda(np.std(todos_valores))],
            'Valor Total': [formatar_moeda(np.sum(todos_valores))],
            'Valor Mínimo': [formatar_moeda(np.min(todos_valores))],
            'Valor Máximo': [formatar_moeda(np.max(todos_valores))]
        })

        print("\n🌎 ESTATÍSTICA GERAL (A PARTIR DE 1995):")
        display(geral)

        # Análise adicional por período
        print("\n📅 ANÁLISE TEMPORAL (A PARTIR DE 1995):")
        df_temporal = df.copy()

        # Converter valores monetários
        for cidade in colunas_cidades:
            df_temporal[cidade] = df_temporal[cidade].apply(limpar_valor_monetario)

        # Calcular média por período
        df_temporal['Média_Período'] = df_temporal[colunas_cidades].mean(axis=1)
        df_temporal_display = df_temporal[['mes-ano', 'Média_Período']].copy()
        df_temporal_display['Média_Período'] = df_temporal_display['Média_Período'].apply(formatar_moeda)

        print("Média por período:")
        display(df_temporal_display)
        df_temporal.to_html()

    else:
        print("❌ Não foi possível processar os dados")
        print("Estrutura das colunas:", df.columns.tolist())
        print("Primeiras linhas:")
        display(df.head())
else:
    print("❌ Nenhuma cidade foi identificada ou processada")
    print("Estrutura das colunas:", df.columns.tolist())
    print("Amostra dos dados:")
    display(df.head())

📊 DADOS ORIGINAIS:

<ipython-input-29-f27f702bc3c5>:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(to_replace=r'\r|\n', value='', regex=True)

0    mes-ano  Belo Horizonte  Rio de Janeiro  São Paulo  Vitória
0    01-1989           42.14           44.75      44.95    42.56
1    02-1989           51.00           51.86      51.23    52.17
2    03-1989           55.23           56.37      56.45    54.43
3    04-1989           55.84           57.46      60.14    58.73
4    05-1989           69.59           72.99      72.90    75.41
..       ...             ...             ...        ...      ...
428  08-2024          655.25          745.64     786.35   684.21
429  09-2024          651.44          757.30     792.47   694.87
430  10-2024          678.07          773.70     805.84   708.06
431  11-2024          686.90          777.66     828.39   726.51
432  12-2024          694.77          779.84     841.29   747.42

[433 rows x 5 columns]

DADOS FILTRADOS A PARTIR DE 1995:

🏙️ Cidades identificadas: ['Belo Horizonte', 'Rio de Janeiro', 'São Paulo', 'Vitória']

📈 ESTATÍSTICAS POR CIDADE (A PARTIR DE 1995):

<ipython-input-29-f27f702bc3c5>:52: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_filtered = df[df['mes-ano'].str.contains(r'(199[5-9]|20[0-9]{2})', na=False)]

,Cidade,Registros,Média,Mediana,Desvio Padrão,Mínimo,Máximo,Soma Total
0,Belo Horizonte,360,"R$ 281,01","R$ 228,98","R$ 181,70","R$ 74,74","R$ 727,46","R$ 101.164,29"
1,Rio de Janeiro,361,"R$ 303,56","R$ 225,26","R$ 209,66","R$ 74,37","R$ 832,80","R$ 109.583,88"
2,São Paulo,361,"R$ 316,24","R$ 241,08","R$ 214,61","R$ 83,79","R$ 841,29","R$ 114.162,62"
3,Vitória,361,"R$ 290,95","R$ 227,54","R$ 199,55","R$ 70,07","R$ 747,42","R$ 105.033,96"

🌎 ESTATÍSTICA GERAL (A PARTIR DE 1995):

,Métrica,Total de Registros,Média Geral,Mediana Geral,Desvio Padrão Geral,Valor Total,Valor Mínimo,Valor Máximo
0,Geral (Todas as Cidades),1443,"R$ 297,95","R$ 231,12","R$ 201,94","R$ 429.944,75","R$ 70,07","R$ 841,29"

📅 ANÁLISE TEMPORAL (A PARTIR DE 1995):
Média por período:

0    mes-ano Média_Período
72   01-1995      R$ 78,70
73   02-1995      R$ 76,98
74   03-1995      R$ 80,39
75   04-1995      R$ 88,25
76   05-1995      R$ 89,03
..       ...           ...
428  08-2024     R$ 717,86
429  09-2024     R$ 724,02
430  10-2024     R$ 741,42
431  11-2024     R$ 754,87
432  12-2024     R$ 765,83

[361 rows x 2 columns]